// Generated by gencpp from file server/addInt.msg
// DO NOT EDIT!


#ifndef SERVER_MESSAGE_ADDINT_H
#define SERVER_MESSAGE_ADDINT_H

#include <ros/service_traits.h>


#include <server/addIntRequest.h>
#include <server/addIntResponse.h>


namespace server
{

struct addInt
{

typedef addIntRequest Request;
typedef addIntResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct addInt
} // namespace server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::server::addInt > {
  static const char* value()
  {
    return "f0b6d69ea10b0cf210cb349d58d59e8f";
  }

  static const char* value(const ::server::addInt&) { return value(); }
};

template<>
struct DataType< ::server::addInt > {
  static const char* value()
  {
    return "server/addInt";
  }

  static const char* value(const ::server::addInt&) { return value(); }
};


// service_traits::MD5Sum< ::server::addIntRequest> should match
// service_traits::MD5Sum< ::server::addInt >
template<>
struct MD5Sum< ::server::addIntRequest>
{
  static const char* value()
  {
    return MD5Sum< ::server::addInt >::value();
  }
  static const char* value(const ::server::addIntRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::server::addIntRequest> should match
// service_traits::DataType< ::server::addInt >
template<>
struct DataType< ::server::addIntRequest>
{
  static const char* value()
  {
    return DataType< ::server::addInt >::value();
  }
  static const char* value(const ::server::addIntRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::server::addIntResponse> should match
// service_traits::MD5Sum< ::server::addInt >
template<>
struct MD5Sum< ::server::addIntResponse>
{
  static const char* value()
  {
    return MD5Sum< ::server::addInt >::value();
  }
  static const char* value(const ::server::addIntResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::server::addIntResponse> should match
// service_traits::DataType< ::server::addInt >
template<>
struct DataType< ::server::addIntResponse>
{
  static const char* value()
  {
    return DataType< ::server::addInt >::value();
  }
  static const char* value(const ::server::addIntResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVER_MESSAGE_ADDINT_H
